# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20170602_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default='2000/01/01', max_length=8),
        ),
    ]
